# .github/FUNDING.yml
# Dymi is fully open-source and does not accept personal donations.
# If you want to support good causes, click the links below.

custom:
  - https://www.givewell.org/donate
  - https://www.effectivealtruism.org/donate
  - https://www.unicef.org/donate
  - https://www.khanacademy.org/donate
