# .github/FUNDING.yml
# Dymi is fully open-source. All support goes directly to charities.

custom:
  - name: "GiveWell – High-Impact Global Charities"
    url: "https://www.givewell.org/donate"
  - name: "Effective Altruism Fund – Top Priority Causes"
    url: "https://www.effectivealtruism.org/donate"
  - name: "UNICEF – Child Welfare & Humanitarian Aid"
    url: "https://www.unicef.org/donate"
  - name: "Khan Academy – Free Education Worldwide"
    url: "https://www.khanacademy.org/donate"
