# .github/FUNDING.yml
# All support for Dymi goes directly to charities and global good causes.

custom:
  - https://www.givewell.org/donate # Evidence-based, high-impact global charities
  - https://www.effectivealtruism.org/donate # Supports top-priority causes worldwide
  - https://www.unicef.org/donate # Child welfare and humanitarian aid
  - https://www.khanacademy.org/donate # Free global education
