# FUNDING.yml
# This project does NOT accept personal donations.
# Any support is redirected to verified charities and public-good causes.

custom:
  - https://www.givewell.org
  - https://www.effectivealtruism.org/donate
  - https://www.unicef.org/donate
  - https://www.khanacademy.org/donate
