# .github/FUNDING.yml
# All funding for Dymi is redirected to charities and public-good causes.

github:
  - DymiCharityRedirect       # GitHub Sponsors account that donates 100% to charities

open_collective: dymi-community  # Community fund, fully transparent

liberapay: dymi-community        # Recurring support, fully open

custom:
  - https://www.givewell.org/donate
  - https://www.effectivealtruism.org/donate
  - https://www.unicef.org/donate
  - https://www.khanacademy.org/donate
